package ai

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"
	"mandor/internal/ai"
	"mandor/internal/domain"
)

func NewClaudeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "claude",
		Short: "Generate CLAUDE.md for the project",
		RunE: func(cmd *cobra.Command, args []string) error {
			projectRoot, err := ai.FindProjectRoot()
			if err != nil {
				return domain.NewValidationError("failed to find project root: " + err.Error())
			}

			now := time.Now().UTC().Format("2006-01-02")
			projectName := filepath.Base(projectRoot)

			content := generateAIDoc(projectName, now)

			targetPath := filepath.Join(projectRoot, "CLAUDE.md")

			if err := os.WriteFile(targetPath, []byte(content), 0644); err != nil {
				return domain.NewSystemError("failed to write file", err)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Generated: %s\n", targetPath)
			return nil
		},
	}

	return cmd
}

func generateAIDoc(projectName, createdAt string) string {
	return "# DEVELOPMENT GUIDELINES\n\n" +
		"---\n\n" +
		"## Project Context\n\n" +
		fmt.Sprintf("- **Project**: %s\n", projectName) +
		fmt.Sprintf("- **Mandor Version**: 0.0.1\n") +
		fmt.Sprintf("- **Workspace Created**: %s\n", createdAt) +
		"\nThis project uses Mandor CLI for event-based task management. All tasks, features, and issues are tracked through Mandor.\n" +
		"\n---\n\n" +
		"# CRITICAL RULES GUIDELINES\n\n" +
		"Run `mandor populate` to see how to use mandor commands. Must using mandor for development.\n" +
		"\n---\n\n" +
		fmt.Sprintf("*Generated by Mandor CLI 0.0.1*\n") +
		fmt.Sprintf("*Last updated: %s*\n", createdAt)
}
