package templates

import (
	"fmt"
	"strings"
	"time"
)

type AgentsTemplateData struct {
	ProjectName   string
	Goal          string
	MandorVersion string
	AgentCount    int
	Protocol      string
	CreatedAt     string
}

func GenerateAgentsMD(data AgentsTemplateData) string {
	now := time.Now().UTC().Format("2006-01-02")

	var sb strings.Builder

	sb.WriteString("# DEVELOPMENT GUIDELINES\n\n")
	sb.WriteString("---\n\n")

	sb.WriteString("## Project Context\n\n")
	sb.WriteString(fmt.Sprintf("- **Project**: %s\n", data.ProjectName))
	sb.WriteString(fmt.Sprintf("- **Goal**: %s\n", data.Goal))
	sb.WriteString(fmt.Sprintf("- **Mandor Version**: %s\n", data.MandorVersion))
	sb.WriteString(fmt.Sprintf("- **Workspace Created**: %s\n", data.CreatedAt))
	sb.WriteString("\nThis project uses Mandor CLI for event-based task management. All tasks, features, and issues are tracked through Mandor.\n")

	sb.WriteString("\n---\n\n")

	sb.WriteString("# CRITICAL RULES GUIDELINES\n\n")
	sb.WriteString("Run `mandor populate` to see how to use mandor commands. Must using mandor for development.\n")

	sb.WriteString("\n---\n\n")

	sb.WriteString(fmt.Sprintf("*Generated by Mandor CLI %s*\n", data.MandorVersion))
	sb.WriteString(fmt.Sprintf("*Last updated: %s*\n", now))

	return sb.String()
}
